### ISSUE TITLE
Sprockets asset does not support method close

### ISSUE THREAD

**Issue by deric** [ezrondre/speedup-rails#2]
Currently the gem doesn't seem to work with sprockets:
```
[2015-06-09 15:33:56] ERROR NoMethodError: undefined method `close' for #<Sprockets::Asset:0x007fcc1f7dc330>
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/speedup-rails-0.0.3/lib/speedup/middleware.rb:53:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/body_proxy.rb:16:in `close'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:118:in `service'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        /home/deric/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

a fix might be relatively easy:
```
@rack_body.close if (@rack_body != nil and @rack_body.respond_to? :close)
```

**Comment by phoenixek12** [comment]
I have done this, so it should work now, but the body should not be build in asset request...
New gem version is published.

**Comment by deric** [comment]
ok, thanks!
